import sys

file_path = r"e:\project\workspace\WOS-Commander\app\growth\events.tsx"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Marks
start_ternary = -1
for i, line in enumerate(lines):
    if "{editingEvent?.id === 'a_fortress' || editingEvent?.id === 'a_citadel' ? (" in line and i > 3200:
        start_ternary = i
        break

end_ternary = -1
for i, line in enumerate(lines):
    if "{/* Schedule Modal Footer */}" in line:
        for j in range(i-1, start_ternary, -1):
            if "            </View>" in lines[j]:
                end_ternary = j + 1
                break
        if end_ternary != -1:
            break

if start_ternary == -1 or end_ternary == -1:
    print(f"Markers not found: start={start_ternary}, end={end_ternary}")
    sys.exit(1)

# Complete Re-implementation of the Ternary Block
new_ternary_content = [
    "                                {editingEvent?.id === 'a_fortress' || editingEvent?.id === 'a_citadel' ? (\n",
    "                                    <View className=\"flex-1 mt-4\">\n",
    "                                        <ScrollView contentContainerStyle={{ paddingBottom: 20 }} showsVerticalScrollIndicator={false} className=\"flex-1\">\n",
    "                                            <View className=\"mb-2\">\n",
    "                                                <View className=\"flex-row items-center mb-2\">\n",
    "                                                    <Text className=\"text-brand-accent text-[10px] font-bold uppercase opacity-60\">{t('events.modal.registered_schedule')}</Text>\n",
    "                                                </View>\n",
    "                                                <View className=\"flex-row flex-wrap gap-2\">\n",
    "                                                    {(editingEvent?.id === 'a_fortress' ? fortressList : citadelList).map(slot => (\n",
    "                                                        <TouchableOpacity key={slot.id} onPress={() => {\n",
    "                                                            if (editingSlotId === slot.id) {\n",
    "                                                                setEditingSlotId(null);\n",
    "                                                                setSelectedFortressName('');\n",
    "                                                            } else {\n",
    "                                                                setEditingSlotId(slot.id);\n",
    "                                                                setSelectedFortressName(slot.name);\n",
    "                                                                setSelectedDayForSlot(slot.day || '토');\n",
    "                                                                setEditHour(slot.h);\n",
    "                                                                setEditMinute(slot.m);\n",
    "                                                            }\n",
    "                                                        }} className={`border px-3 py-1.5 rounded-xl flex-row items-center ${editingSlotId === slot.id ? 'bg-brand-accent/30 border-brand-accent' : 'bg-brand-accent/10 border-brand-accent/20'}`}>\n",
    "                                                            <Text className=\"text-white text-xs font-bold mr-2\">{slot.name} {t(`events.days.${['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'][['일', '월', '화', '수', '목', '금', '토'].indexOf(slot.day || '토')]}`)}({slot.h}:{slot.m})</Text>\n",
    "                                                            <TouchableOpacity hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }} onPress={() => removeFortressSlot(slot.id)}><Ionicons name=\"close-circle\" size={16} color=\"#ef4444\" /></TouchableOpacity>\n",
    "                                                        </TouchableOpacity>\n",
    "                                                    ))}\n",
    "                                                    {(editingEvent?.id === 'a_fortress' ? fortressList : citadelList).length === 0 && (\n",
    "                                                        <View className={`w-full h-8 flex-row items-center justify-center border border-dashed rounded-xl ${isDark ? 'border-amber-500/30 bg-amber-500/5' : 'border-amber-500/50 bg-amber-50'}`}>\n",
    "                                                            <Ionicons name=\"alert-circle-outline\" size={14} color={isDark ? \"#fbbf24\" : \"#d97706\"} style={{ marginRight: 6 }} />\n",
    "                                                            <Text className={`text-[11px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-600'}`}>{t('events.modal.no_schedule')}</Text>\n",
    "                                                        </View>\n",
    "                                                    )}\n",
    "                                                </View>\n",
    "                                            </View>\n",
    "\n",
    "                                            <View className={`mb-4 p-3 rounded-xl border ${isDark ? 'bg-slate-800/30 border-slate-700' : 'bg-slate-50 border-slate-200'}`}>\n",
    "                                                <View className=\"flex-row items-center justify-between\">\n",
    "                                                    <View className=\"flex-row items-center flex-1\">\n",
    "                                                        <Ionicons name=\"calendar-number-outline\" size={16} color=\"#0ea5e9\" style={{ marginRight: 8 }} />\n",
    "                                                        <Text className={`text-sm font-bold ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>{t('events.specify_date')}</Text>\n",
    "                                                    </View>\n",
    "                                                    <Switch\n",
    "                                                        value={enableStartDate}\n",
    "                                                        onValueChange={setEnableStartDate}\n",
    "                                                        trackColor={{ false: isDark ? '#334155' : '#cbd5e1', true: '#0ea5e9' }}\n",
    "                                                        thumbColor={enableStartDate ? '#ffffff' : '#94a3b8'}\n",
    "                                                    />\n",
    "                                                </View>\n",
    "                                                {enableStartDate && (\n",
    "                                                    <TouchableOpacity\n",
    "                                                        onPress={() => setShowDatePicker('startDate')}\n",
    "                                                        className={`mt-3 p-2.5 rounded-lg border ${isDark ? 'bg-slate-900/40 border-slate-600' : 'bg-white border-slate-300'}`}\n",
    "                                                    >\n",
    "                                                        <View className=\"flex-row items-center justify-between\">\n",
    "                                                            <Text className={`font-mono text-base ${eventStartDate ? (isDark ? 'text-white' : 'text-slate-900') : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>\n",
    "                                                                {eventStartDate || 'YYYY.MM.DD'}\n",
    "                                                            </Text>\n",
    "                                                            <Ionicons name=\"calendar-outline\" size={18} color=\"#0ea5e9\" />\n",
    "                                                        </View>\n",
    "                                                    </TouchableOpacity>\n",
    "                                                )}\n",
    "                                            </View>\n",
    "\n",
    "                                            <View className={`p-4 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-100 border-slate-200'}`}>\n",
    "                                                <View className=\"mb-4\">\n",
    "                                                    <Text className=\"text-brand-accent text-[10px] font-bold uppercase opacity-60 mb-2\">{editingEvent?.id === 'a_fortress' ? t('events.select_fortress') : t('events.select_citadel')}</Text>\n",
    "                                                    <TouchableOpacity onPress={() => setActiveNamePickerId('fortress_picker')} className={`flex-row items-center justify-between p-3 rounded-xl border ${isDark ? 'bg-slate-900/60 border-slate-700' : 'bg-white border-slate-200'}`}>\n",
    "                                                        <View className=\"flex-row items-center\">\n",
    "                                                            <Ionicons name=\"map-outline\" size={18} color=\"#0ea5e9\" style={{ marginRight: 10 }} />\n",
    "                                                            <Text className={`font-bold ${selectedFortressName ? (isDark ? 'text-white' : 'text-slate-900') : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>{selectedFortressName || (editingEvent?.id === 'a_fortress' ? t('events.select_fortress') : t('events.select_citadel'))}</Text>\n",
    "                                                        </View>\n",
    "                                                        <Ionicons name=\"chevron-down\" size={18} color={isDark ? \"#475569\" : \"#94a3b8\"} />\n",
    "                                                    </TouchableOpacity>\n",
    "                                                </View>\n",
    "\n",
    "                                                <View className=\"flex-row gap-3 mb-4\">\n",
    "                                                    <View className=\"flex-1\">\n",
    "                                                        <Text className=\"text-brand-accent text-[10px] font-bold uppercase opacity-60 mb-2\">{t('events.day_of_week')}</Text>\n",
    "                                                        <TouchableOpacity onPress={() => setActiveFortressDropdown('day_picker' as any)} className={`flex-row items-center justify-between p-3 rounded-xl border ${isDark ? 'bg-slate-900/60 border-slate-700' : 'bg-white border-slate-200'}`}>\n",
    "                                                            <Text className={`font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>{t(`events.days.${['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'][['일', '월', '화', '수', '목', '금', '토'].indexOf(selectedDayForSlot || '토')]}`)}</Text>\n",
    "                                                            <Ionicons name=\"chevron-down\" size={14} color={isDark ? \"#475569\" : \"#94a3b8\"} />\n",
    "                                                        </TouchableOpacity>\n",
    "                                                    </View>\n",
    "                                                    <View className=\"flex-[1.5]\">\n",
    "                                                        <Text className=\"text-brand-accent text-[10px] font-bold uppercase opacity-60 mb-2\">{t('events.modal.select_time')}</Text>\n",
    "                                                        <View className=\"flex-row items-center gap-1\">\n",
    "                                                            <TouchableOpacity onPress={() => setActiveFortressDropdown('hour_picker' as any)} className={`flex-1 flex-row items-center justify-between p-3 rounded-xl border ${isDark ? 'bg-slate-900/60 border-slate-700' : 'bg-white border-slate-200'}`}>\n",
    "                                                                <Text className={`font-mono font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>{editHour}</Text>\n",
    "                                                                <Ionicons name=\"chevron-down\" size={14} color={isDark ? \"#475569\" : \"#94a3b8\"} />\n",
    "                                                            </TouchableOpacity>\n",
    "                                                            <Text className={`font-bold ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>:</Text>\n",
    "                                                            <TouchableOpacity onPress={() => setActiveFortressDropdown('minute_picker' as any)} className={`flex-1 flex-row items-center justify-between p-3 rounded-xl border ${isDark ? 'bg-slate-900/60 border-slate-700' : 'bg-white border-slate-200'}`}>\n",
    "                                                                <Text className={`font-mono font-bold ${isDark ? 'text-white' : 'text-slate-900'}`}>{editMinute}</Text>\n",
    "                                                                <Ionicons name=\"chevron-down\" size={14} color={isDark ? \"#475569\" : \"#94a3b8\"} />\n",
    "                                                            </TouchableOpacity>\n",
    "                                                        </View>\n",
    "                                                    </View>\n",
    "                                                </View>\n",
    "\n",
    "                                                <TouchableOpacity onPress={addFortressSlot} className={`w-full py-4 rounded-xl items-center flex-row justify-center border ${editingSlotId ? 'bg-emerald-500/20 border-emerald-500/40' : 'bg-brand-accent border-brand-accent'}`}>\n",
    "                                                    <Ionicons name={editingSlotId ? \"checkmark-circle\" : \"add-circle-outline\"} size={20} color={editingSlotId ? \"#10b981\" : \"black\"} style={{ marginRight: 8 }} />\n",
    "                                                    <Text className={`font-bold text-base ${editingSlotId ? 'text-emerald-400' : 'text-brand-dark'}`}>{editingSlotId ? t('events.edit_completed') : t('events.modal.add_time_slot')}</Text>\n",
    "                                                </TouchableOpacity>\n",
    "                                                {!!editingSlotId && (\n",
    "                                                    <TouchableOpacity onPress={() => { setEditingSlotId(null); setSelectedFortressName(''); }} className=\"mt-2 w-full py-3 rounded-xl items-center border border-slate-700/50 bg-slate-800/30\">\n",
    "                                                        <Text className=\"text-slate-400 font-semibold\">{t('common.cancel')}</Text>\n",
    "                                                    </TouchableOpacity>\n",
    "                                                )}\n",
    "                                            </View>\n",
    "                                        </ScrollView>\n",
    "                                    </View>\n",
    "                                ) : (\n",
    "                                    <View className=\"flex-1\" style={{ overflow: 'visible', zIndex: (hourDropdownVisible || minuteDropdownVisible) ? 200 : 1 }}>\n",
    "                                        {(() => {\n",
    "                                            const singleSlotIDs = ['a_center', 'alliance_center', 'a_mercenary', 'alliance_mercenary', 'a_immigrate', 'alliance_immigrate', 'a_merge', 'alliance_merge', 'a_svs', 'alliance_svs', 'a_dragon', 'alliance_dragon', 'a_joe', 'alliance_joe', 'alliance_champion'];\n",
    "                                            if (editingEvent?.category === '연맹' && !singleSlotIDs.includes(editingEvent.id)) {\n",
    "                                                return (\n",
    "                                                    <View className={`flex-row mb-2 p-1 rounded-xl ${isDark ? 'bg-slate-800' : 'bg-slate-100'}`}>\n",
    "                                                        <TouchableOpacity onPress={() => handleTabSwitch(1)} className={`flex-1 py-1.5 items-center rounded-lg ${activeTab === 1 ? (isDark ? 'bg-slate-700 shadow-sm' : 'bg-white shadow-sm') : ''}`}><Text className={`font-semibold text-xs ${activeTab === 1 ? (isDark ? 'text-white' : 'text-sky-600') : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>{(editingEvent?.id === 'a_bear' || editingEvent?.id === 'alliance_bear') ? t('events.bear1_setting') : t('events.team1_setting')}</Text></TouchableOpacity>\n",
    "                                                        <TouchableOpacity onPress={() => handleTabSwitch(2)} className={`flex-1 py-1.5 items-center rounded-lg ${activeTab === 2 ? (isDark ? 'bg-slate-700 shadow-sm' : 'bg-white shadow-sm') : ''}`}><Text className={`font-semibold text-xs ${activeTab === 2 ? (isDark ? 'text-white' : 'text-sky-600') : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>{(editingEvent?.id === 'a_bear' || editingEvent?.id === 'alliance_bear') ? t('events.bear2_setting') : t('events.team2_setting')}</Text></TouchableOpacity>\n",
    "                                                    </View>\n",
    "                                                );\n",
    "                                            }\n",
    "                                            return null;\n",
    "                                        })()}\n",
    "\n",
    "                                        <ScrollView contentContainerStyle={{ flexGrow: 1, paddingBottom: 150 }} showsVerticalScrollIndicator={false} className=\"flex-1\">\n",
    "                                            <View className=\"flex-1 justify-between pb-4\">\n",
    "                                                {editingEvent?.id !== 'a_center' && (\n",
    "                                                    <View className=\"mb-2\">\n",
    "                                                        <View className=\"flex-row items-center mb-2\">\n",
    "                                                            <Text className=\"text-brand-accent text-[10px] font-bold uppercase opacity-60\">{t('events.modal.registered_schedule')}</Text>\n",
    "                                                        </View>\n",
    "                                                        <View className=\"flex-row flex-wrap gap-2\">\n",
    "                                                            {(activeTab === 1 ? slots1 : slots2).map(slot => {\n",
    "                                                                if (slot.isNew) {\n",
    "                                                                    const backgroundColor = newSlotPulse.interpolate({\n",
    "                                                                        inputRange: [0, 1],\n",
    "                                                                        outputRange: ['rgba(251, 191, 36, 0.1)', 'rgba(251, 191, 36, 0.4)']\n",
    "                                                                    });\n",
    "                                                                    const borderColor = newSlotPulse.interpolate({\n",
    "                                                                        inputRange: [0, 1],\n",
    "                                                                        outputRange: ['rgba(251, 191, 36, 0.3)', 'rgba(251, 191, 36, 0.8)']\n",
    "                                                                    });\n",
    "                                                                    return (\n",
    "                                                                        <TouchableOpacity key={slot.id} onPress={() => { const [h, m] = slot.time.split(':'); setEditHour(h || '22'); setEditMinute(m || '00'); setSelectedDayForSlot(slot.day); if (editingSlotId === slot.id) { setEditingSlotId(null); setEditHour('22'); setEditMinute('00'); } else { setEditingSlotId(slot.id); } }}>\n",
    "                                                                            <Animated.View style={{ backgroundColor, borderColor, borderWidth: 1 }} className={`px-3 py-1.5 rounded-xl flex-row items-center border`}>\n",
    "                                                                                <Text className={`text-amber-400 text-xs font-bold mr-2`}>{t(`events.days.${['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'daily', 'always'][['일', '월', '화', '수', '목', '금', '토', '매일', '상시'].indexOf(slot.day)]}`)}{slot.time ? `(${formatTime24h(slot.time)})` : ''}</Text>\n",
    "                                                                                <TouchableOpacity hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }} onPress={() => removeTimeSlot(slot.id)}><Ionicons name=\"close-circle\" size={16} color=\"#fbbf24\" /></TouchableOpacity>\n",
    "                                                                            </Animated.View>\n",
    "                                                                        </TouchableOpacity>\n",
    "                                                                    );\n",
    "                                                                }\n",
    "                                                                return (\n",
    "                                                                    <TouchableOpacity key={slot.id} onPress={() => { const [h, m] = slot.time.split(':'); setEditHour(h || '22'); setEditMinute(m || '00'); setSelectedDayForSlot(slot.day); if (editingSlotId === slot.id) { setEditingSlotId(null); setEditHour('22'); setEditMinute('00'); } else { setEditingSlotId(slot.id); } }} className={`border px-3 py-1.5 rounded-xl flex-row items-center ${editingSlotId === slot.id ? 'bg-brand-accent/30 border-brand-accent' : 'bg-brand-accent/10 border-brand-accent/20'}`}><Text className=\"text-white text-xs font-bold mr-2\">{t(`events.days.${['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'daily', 'always'][['일', '월', '화', '수', '목', '금', '토', '매일', '상시'].indexOf(slot.day)]}`)}{slot.time ? `(${formatTime24h(slot.time)})` : ''}</Text><TouchableOpacity hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }} onPress={() => removeTimeSlot(slot.id)}><Ionicons name=\"close-circle\" size={16} color=\"#ef4444\" /></TouchableOpacity></TouchableOpacity>\n",
    "                                                                );\n",
    "                                                            })}\n",
    "                                                            {(activeTab === 1 ? slots1 : slots2).length === 0 && (\n",
    "                                                                <View className={`w-full h-8 flex-row items-center justify-center border border-dashed rounded-xl ${isDark ? 'border-amber-500/30 bg-amber-500/5' : 'border-amber-500/50 bg-amber-50'}`}>\n",
    "                                                                    <Ionicons name=\"alert-circle-outline\" size={14} color={isDark ? \"#fbbf24\" : \"#d97706\"} style={{ marginRight: 6 }} />\n",
    "                                                                    <Text className={`text-[11px] font-bold ${isDark ? 'text-amber-400' : 'text-amber-600'}`}>{t('events.modal.no_schedule')}</Text>\n",
    "                                                                </View>\n",
    "                                                            )}\n",
    "                                                        </View>\n",
    "                                                    </View>\n",
    "                                                )}\n",
    "\n",
    "                                                {editingEvent?.id !== 'a_center' && (\n",
    "                                                    <View className={`p-4 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-100 border-slate-200'}`}>\n",
    "                                                        <View className=\"mb-4\">\n",
    "                                                            <View className=\"flex-row items-center justify-between mb-3\">\n",
    "                                                                <View className=\"flex-row items-center\">\n",
    "                                                                    <Ionicons name=\"calendar-number-outline\" size={14} color={isDark ? \"#94a3b8\" : \"#64748b\"} style={{ marginRight: 6 }} />\n",
    "                                                                    <Text className=\"text-brand-accent text-xs font-bold uppercase\">{t('events.specify_date')}</Text>\n",
    "                                                                </View>\n",
    "                                                                <Switch\n",
    "                                                                    value={enableStartDate}\n",
    "                                                                    onValueChange={setEnableStartDate}\n",
    "                                                                    trackColor={{ false: '#64748b', true: '#3b82f6' }}\n",
    "                                                                    thumbColor='white'\n",
    "                                                                    style={{ transform: [{ scale: 0.8 }] }}\n",
    "                                                                />\n",
    "                                                            </View>\n",
    "                                                            {enableStartDate && (\n",
    "                                                                <TouchableOpacity\n",
    "                                                                    onPress={() => setShowDatePicker('startDate')}\n",
    "                                                                    className={`p-3 rounded-xl border ${isDark ? 'bg-slate-900/40 border-slate-700' : 'bg-white border-slate-200'}`}\n",
    "                                                                >\n",
    "                                                                    <View className=\"flex-row items-center justify-between\">\n",
    "                                                                        <View className=\"flex-1\">\n",
    "                                                                            <Text className={`text-[10px] font-bold mb-1 ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>{t('events.select_date')}</Text>\n",
    "                                                                            <Text className={`font-mono text-sm ${eventStartDate ? (isDark ? 'text-white' : 'text-slate-900') : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>{eventStartDate || 'YYYY.MM.DD'}</Text>\n",
    "                                                                        </View>\n",
    "                                                                        <Ionicons name=\"calendar\" size={20} color=\"#0ea5e9\" />\n",
    "                                                                    </View>\n",
    "                                                                </TouchableOpacity>\n",
    "                                                            )}\n",
    "                                                        </View>\n",
    "\n",
    "                                                        {selectedDayForSlot !== '상시' ? (\n",
    "                                                            <>\n",
    "                                                                <View className=\"mb-4\">\n",
    "                                                                    <View className=\"flex-row items-center mb-2\">\n",
    "                                                                        <Ionicons name=\"calendar-outline\" size={14} color={isDark ? \"#94a3b8\" : \"#64748b\"} style={{ marginRight: 6 }} />\n",
    "                                                                        <Text className=\"text-brand-accent text-xs font-bold uppercase\">{t('events.day_of_week')}</Text>\n",
    "                                                                    </View>\n",
    "                                                                    {editingEvent?.id === 'a_mercenary' || editingEvent?.id === 'alliance_mercenary' ? (\n",
    "                                                                        <View className=\"flex-row items-center justify-center\">\n",
    "                                                                            <TouchableOpacity onPress={() => dayWheelRef.current?.scrollTo({ x: (Math.round(currentScrollX / 80) - 1) * 80, animated: true })} className={`p-2 ${isDark ? 'bg-slate-800' : 'bg-slate-100'} rounded-full mr-1`}><Ionicons name=\"chevron-back\" size={16} color={isDark ? \"#94a3b8\" : \"#64748b\"} /></TouchableOpacity>\n",
    "                                                                            <View className=\"relative h-14 w-[240px] overflow-hidden bg-slate-800/20 rounded-xl\">\n",
    "                                                                                <View pointerEvents=\"none\" style={{ position: 'absolute', width: 80, height: 40, left: 80, top: 7, borderWidth: 2, borderColor: '#38bdf8', borderRadius: 12, backgroundColor: '#38bdf81a', zIndex: 5 }} />\n",
    "                                                                                <ScrollView ref={dayWheelRef} horizontal showsHorizontalScrollIndicator={false} snapToInterval={80} decelerationRate=\"fast\" scrollEventThrottle={16} onScroll={(e) => setCurrentScrollX(e.nativeEvent.contentOffset.x)} onMomentumScrollEnd={(e) => {\n",
    "                                                                                    const x = e.nativeEvent.contentOffset.x;\n",
    "                                                                                    const itemIndexInLens = Math.round(x / 80) + 1;\n",
    "                                                                                    const days = ['월', '화', '수', '목', '금', '토', '일'];\n",
    "                                                                                    const realIndex = (itemIndexInLens % 7 + 7) % 7;\n",
    "                                                                                    setSelectedDayForSlot(days[realIndex]);\n",
    "                                                                                    if (itemIndexInLens < 7 || itemIndexInLens >= 14) {\n",
    "                                                                                        const targetItemIndex = 7 + realIndex;\n",
    "                                                                                        const targetX = (targetItemIndex - 1) * 80;\n",
    "                                                                                        dayWheelRef.current?.scrollTo({ x: targetX, animated: false });\n",
    "                                                                                        setCurrentScrollX(targetX);\n",
    "                                                                                    }\n",
    "                                                                                }} contentContainerStyle={{ paddingHorizontal: 0, alignItems: 'center' }}>\n",
    "                                                                                    {[...['월', '화', '수', '목', '금', '토', '일'], ...['월', '화', '수', '목', '금', '토', '일'], ...['월', '화', '수', '목', '금', '토', '일']].map((d, index) => {\n",
    "                                                                                        const enKeys = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];\n",
    "                                                                                        return (\n",
    "                                                                                            <TouchableOpacity key={`${d}-${index}`} onPress={() => { setSelectedDayForSlot(d); dayWheelRef.current?.scrollTo({ x: (index - 1) * 80, animated: true }); }} style={{ width: 80, height: 40, alignItems: 'center', justifyContent: 'center', zIndex: 10 }} activeOpacity={0.7}><Text className={`font-black tracking-tighter text-center ${selectedDayForSlot === d ? 'text-sky-400 text-lg scale-110' : (isDark ? 'text-slate-600' : 'text-slate-400')}`} style={{ lineHeight: 40 }}>{t(`events.days.${enKeys[index % 7]}`)}</Text>{selectedDayForSlot === d && <View className=\"absolute bottom-1 w-1.5 h-1.5 rounded-full bg-sky-500\" />}</TouchableOpacity>\n",
    "                                                                                        );\n",
    "                                                                                    })}\n",
    "                                                                                </ScrollView>\n",
    "                                                                            </View>\n",
    "                                                                            <TouchableOpacity onPress={() => dayWheelRef.current?.scrollTo({ x: (Math.round(currentScrollX / 80) + 1) * 80, animated: true })} className={`p-2 ${isDark ? 'bg-slate-800' : 'bg-slate-100'} rounded-full ml-1`}><Ionicons name=\"chevron-forward\" size={16} color={isDark ? \"#94a3b8\" : \"#64748b\"} /></TouchableOpacity>\n",
    "                                                                        </View>\n",
    "                                                                    ) : (\n",
    "                                                                        <View className=\"flex-row flex-wrap justify-between gap-1\">\n",
    "                                                                            {['월', '화', '수', '목', '금', '토', '일', '상시'].map((d) => {\n",
    "                                                                                const isSelected = selectedDayForSlot === d;\n",
    "                                                                                const dayLabel = d === '월' ? t('events.days.mon') : d === '화' ? t('events.days.tue') : d === '수' ? t('events.days.wed') : d === '목' ? t('events.days.thu') : d === '금' ? t('events.days.fri') : d === '토' ? t('events.days.sat') : d === '일' ? t('events.days.sun') : t('events.days.always');\n",
    "                                                                                return (\n",
    "                                                                                    <TouchableOpacity key={d} onPress={() => toggleDay(d)} className={`w-[11%] h-9 rounded-lg items-center justify-center border ${isSelected ? 'bg-brand-accent border-brand-accent' : 'bg-slate-800/60 border-slate-700'}`}><Text className={`font-bold text-[10px] ${isSelected ? 'text-brand-dark' : 'text-slate-300'}`}>{dayLabel}</Text></TouchableOpacity>\n",
    "                                                                                );\n",
    "                                                                            })}\n",
    "                                                                        </View>\n",
    "                                                                    )}\n",
    "                                                                </View>\n",
    "\n",
    "                                                                <View>\n",
    "                                                                    <View className=\"flex-row items-center mb-2\">\n",
    "                                                                        <Ionicons name=\"alarm-outline\" size={14} color={isDark ? \"#94a3b8\" : \"#64748b\"} style={{ marginRight: 6 }} />\n",
    "                                                                        <Text className=\"text-brand-accent text-xs font-bold uppercase\">{t('events.modal.set_time')} (24H)</Text>\n",
    "                                                                    </View>\n",
    "                                                                    {editingEvent?.id === 'a_mercenary' || editingEvent?.id === 'alliance_mercenary' ? (\n",
    "                                                                        <PremiumClockPicker hour={parseInt(editHour)} minute={parseInt(editMinute)} onHourChange={(h) => setEditHour(h.toString().padStart(2, '0'))} onMinuteChange={(m) => setEditMinute(m.toString().padStart(2, '0'))} isDark={isDark} t={t} />\n",
    "                                                                    ) : (\n",
    "                                                                        <>\n",
    "                                                                            <View className=\"flex-row flex-wrap justify-between gap-1 mb-2\">\n",
    "                                                                                {Array.from({ length: 24 }, (_, i) => i).map(h24 => (\n",
    "                                                                                    <TouchableOpacity key={h24} onPress={() => setEditHour(h24.toString().padStart(2, '0'))} className={`w-[15.5%] aspect-square rounded-xl items-center justify-center border ${parseInt(editHour) === h24 ? 'bg-sky-500 border-sky-400' : (isDark ? 'bg-slate-900/40 border-slate-700/50' : 'bg-white border-slate-100')}`}><Text className={`text-[11px] font-bold ${parseInt(editHour) === h24 ? 'text-white' : (isDark ? 'text-slate-400' : 'text-slate-600')}`}>{h24}</Text></TouchableOpacity>\n",
    "                                                                                ))}\n",
    "                                                                            </View>\n",
    "                                                                            <View className=\"flex-row justify-between gap-1\">\n",
    "                                                                                {['00', '10', '20', '30', '40', '50'].map(m => (\n",
    "                                                                                    <TouchableOpacity key={m} onPress={() => setEditMinute(m)} className={`flex-1 py-2 rounded-lg items-center justify-center border ${editMinute === m ? 'bg-sky-500 border-sky-400' : (isDark ? 'bg-slate-900/40 border-slate-700/50' : 'bg-white border-slate-100')}`}><Text className={`text-[10px] font-bold ${editMinute === m ? 'text-white' : (isDark ? 'text-slate-400' : 'text-slate-600')}`}>{m}</Text></TouchableOpacity>\n",
    "                                                                                ))}\n",
    "                                                                            </View>\n",
    "                                                                        </>\n",
    "                                                                    )}\n",
    "                                                                </View>\n",
    "\n",
    "                                                                {editingEvent?.id?.includes('bear') ? (\n",
    "                                                                    editingSlotId ? (\n",
    "                                                                        <View className=\"flex-row gap-2 mt-2\">\n",
    "                                                                            <TouchableOpacity onPress={addTimeSlot} className=\"flex-1 bg-emerald-500/20 border-emerald-500/40 py-4 rounded-xl border items-center flex-row justify-center\"><Ionicons name=\"checkmark-circle\" size={20} color=\"#10b981\" style={{ marginRight: 8 }} /><Text className=\"text-emerald-400 font-bold text-base\">{t('events.edit_completed')}</Text></TouchableOpacity>\n",
    "                                                                            <TouchableOpacity onPress={() => { setEditingSlotId(null); setEditHour('22'); setEditMinute('00'); }} className=\"bg-slate-800 px-4 py-4 rounded-xl border border-slate-700 justify-center\"><Text className=\"text-slate-400 font-semibold text-sm\">{t('common.cancel')}</Text></TouchableOpacity>\n",
    "                                                                        </View>\n",
    "                                                                    ) : (\n",
    "                                                                        <View className=\"mt-3 px-4 py-3 bg-blue-500/10 border border-blue-500/30 rounded-xl\"><Text className=\"text-blue-400 text-sm text-center\">{t('events.modal.bear_hunt_single_time')}</Text></View>\n",
    "                                                                    )\n",
    "                                                                ) : (\n",
    "                                                                    <View className=\"flex-row gap-2 mt-2\">\n",
    "                                                                        <TouchableOpacity onPress={addTimeSlot} className={`flex-1 ${editingSlotId ? 'bg-emerald-500/20 border-emerald-500/40' : 'bg-emerald-500 border-emerald-400'} py-4 rounded-xl border items-center flex-row justify-center`}><Ionicons name={editingSlotId ? \"checkmark-circle\" : \"add-circle-outline\"} size={20} color={editingSlotId ? \"#10b981\" : \"white\"} style={{ marginRight: 8 }} /><Text className={`${editingSlotId ? 'text-emerald-400' : 'text-white'} font-bold text-base`}>{editingSlotId ? t('events.edit_completed') : t('events.modal.add_time_slot')}</Text></TouchableOpacity>\n",
    "                                                                        {!!editingSlotId && <TouchableOpacity onPress={() => { setEditingSlotId(null); setEditHour('22'); setEditMinute('00'); }} className=\"bg-slate-800 px-4 py-4 rounded-xl border border-slate-700 justify-center\"><Text className=\"text-slate-400 font-semibold text-sm\">{t('common.cancel')}</Text></TouchableOpacity>}\n",
    "                                                                    </View>\n",
    "                                                                )}\n",
    "                                                            </>\n",
    "                                                        ) : (\n",
    "                                                            <View className=\"flex-1 justify-center\">\n",
    "                                                                <View>\n",
    "                                                                    <View className=\"flex-row items-center mb-2\"><Ionicons name=\"calendar-outline\" size={14} color={isDark ? \"#94a3b8\" : \"#64748b\"} style={{ marginRight: 6 }} /><Text className=\"text-brand-accent text-xs font-bold uppercase\">{t('events.day_of_week')}</Text></View>\n",
    "                                                                    <View className=\"flex-row flex-wrap justify-between gap-1\">\n",
    "                                                                        {['월', '화', '수', '목', '금', '토', '일', '상시'].map((d) => (\n",
    "                                                                            <TouchableOpacity key={d} onPress={() => toggleDay(d)} className={`w-[11%] h-9 rounded-lg items-center justify-center border ${selectedDayForSlot === d ? 'bg-brand-accent border-brand-accent' : 'bg-slate-800/60 border-slate-700'}`}><Text className={`font-bold text-[10px] ${selectedDayForSlot === d ? 'text-brand-dark' : 'text-slate-300'}`}>{d}</Text></TouchableOpacity>\n",
    "                                                                        ))}\n",
    "                                                                    </View>\n",
    "                                                                </View>\n",
    "                                                                <View className=\"flex-1 justify-center items-center mt-4\"><TouchableOpacity onPress={addTimeSlot} className=\"bg-brand-accent/20 py-4 px-8 rounded-xl border border-brand-accent/40 items-center\"><Text className=\"text-brand-accent font-bold text-lg\">{t('events.days.always')} {t('common.add')}</Text></TouchableOpacity></View>\n",
    "                                                            </View>\n",
    "                                                        )}\n",
    "                                                    </View>\n",
    "                                                )}\n",
    "                                            </View>\n",
    "                                        </ScrollView>\n",
    "                                    </View>\n",
    "                                )}\n"
]

content = lines[:start_ternary] + new_ternary_content + lines[end_ternary:]

with open(file_path, \"w\", encoding=\"utf-8\") as f:
    f.writelines(content)

print(f"Completely re-implemented ternary block from {start_ternary} to {end_ternary}")
